[package]
name = "dungen"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
image = "0.24.6"
env = "0.0.0"
num = "0.4.0"
petgraph = "0.6.3"
